/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import DAO.PacienteDAO_prov;
import Entidad.Paciente;
import javax.swing.JOptionPane;

/**
 *
 * @author tech
 */
public class EgresoPaciente extends javax.swing.JPanel {

    /**
     * Creates new form IngresoPaciente
     */
    public EgresoPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        identificacionTF = new javax.swing.JTextField();
        nombre1L = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        observacionTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        aceptarB = new javax.swing.JButton();
        cancelarB = new javax.swing.JButton();
        nombre2L = new javax.swing.JLabel();
        apellido1L = new javax.swing.JLabel();
        apellido2L = new javax.swing.JLabel();
        tipoAtencioL = new javax.swing.JLabel();
        tipoAtencionL = new javax.swing.JLabel();
        regitroL = new javax.swing.JLabel();
        fechaL = new javax.swing.JLabel();
        rethusL = new javax.swing.JLabel();
        equiposUsados = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        bombaNutricionCB = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        registroTF = new javax.swing.JTextField();
        BuscarB = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(755, 585));
        setPreferredSize(new java.awt.Dimension(755, 585));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        identificacionTF.setBackground(new java.awt.Color(204, 204, 204));
        identificacionTF.setForeground(new java.awt.Color(0, 0, 0));
        identificacionTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identificacionTFActionPerformed(evt);
            }
        });
        add(identificacionTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 6, 145, -1));

        nombre1L.setBackground(new java.awt.Color(0, 0, 0));
        nombre1L.setForeground(new java.awt.Color(0, 0, 0));
        nombre1L.setText("Nombre 1");
        add(nombre1L, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("No. Identificación");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 12, -1, -1));

        observacionTF.setBackground(new java.awt.Color(102, 102, 102));
        add(observacionTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 440, 234, 124));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Observaciones");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 452, -1, -1));

        aceptarB.setBackground(new java.awt.Color(204, 204, 204));
        aceptarB.setForeground(new java.awt.Color(0, 0, 0));
        aceptarB.setText("Aceptar");
        aceptarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarBActionPerformed(evt);
            }
        });
        add(aceptarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 482, 83, -1));

        cancelarB.setBackground(new java.awt.Color(204, 204, 204));
        cancelarB.setForeground(new java.awt.Color(0, 0, 0));
        cancelarB.setText("Cancelar");
        cancelarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBActionPerformed(evt);
            }
        });
        add(cancelarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 521, -1, -1));

        nombre2L.setBackground(new java.awt.Color(0, 0, 0));
        nombre2L.setForeground(new java.awt.Color(0, 0, 0));
        nombre2L.setText("Nombre 2");
        add(nombre2L, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        apellido1L.setBackground(new java.awt.Color(0, 0, 0));
        apellido1L.setForeground(new java.awt.Color(0, 0, 0));
        apellido1L.setText("Apellido 1");
        add(apellido1L, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        apellido2L.setBackground(new java.awt.Color(0, 0, 0));
        apellido2L.setForeground(new java.awt.Color(0, 0, 0));
        apellido2L.setText("Apellido 2");
        add(apellido2L, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 81, -1, -1));

        tipoAtencioL.setBackground(new java.awt.Color(0, 0, 0));
        tipoAtencioL.setForeground(new java.awt.Color(0, 0, 0));
        tipoAtencioL.setText("Tipo de atención");
        add(tipoAtencioL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 102, -1, -1));

        tipoAtencionL.setBackground(new java.awt.Color(0, 0, 0));
        tipoAtencionL.setForeground(new java.awt.Color(0, 0, 0));
        tipoAtencionL.setText("No. de cama");
        add(tipoAtencionL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 123, -1, -1));

        regitroL.setForeground(new java.awt.Color(0, 0, 0));
        regitroL.setText("Registro");
        add(regitroL, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 39, -1, -1));

        fechaL.setForeground(new java.awt.Color(0, 0, 0));
        fechaL.setText("Fecha");
        add(fechaL, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 517, -1, -1));

        rethusL.setForeground(new java.awt.Color(0, 0, 0));
        rethusL.setText("ReTHUS");
        add(rethusL, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 549, -1, -1));

        jCheckBox1.setText("Ventiladores");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Saturometros");

        jCheckBox3.setText("Balas de oxigeno");

        jCheckBox4.setText("monitor cardíaco");

        jCheckBox5.setText("Bomba de infusión continua");

        bombaNutricionCB.setText("Bomba de nutrición");
        bombaNutricionCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bombaNutricionCBActionPerformed(evt);
            }
        });

        jCheckBox7.setText("aspirador de secreciones");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });

        jCheckBox8.setText("equipo de intubacón");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout equiposUsadosLayout = new javax.swing.GroupLayout(equiposUsados);
        equiposUsados.setLayout(equiposUsadosLayout);
        equiposUsadosLayout.setHorizontalGroup(
            equiposUsadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(equiposUsadosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(equiposUsadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox8)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox5)
                    .addComponent(bombaNutricionCB)
                    .addComponent(jCheckBox7))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        equiposUsadosLayout.setVerticalGroup(
            equiposUsadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(equiposUsadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bombaNutricionCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(equiposUsados, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 209, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel4.setText("Equipos usados");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 179, -1, -1));

        registroTF.setBackground(new java.awt.Color(204, 204, 204));
        registroTF.setForeground(new java.awt.Color(0, 0, 0));
        registroTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroTFActionPerformed(evt);
            }
        });
        add(registroTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 39, 145, -1));

        BuscarB.setText("Buscar");
        BuscarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarBActionPerformed(evt);
            }
        });
        add(BuscarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 72, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarBActionPerformed
        Paciente p = new Paciente();
        PacienteDAO_prov dao = new PacienteDAO_prov();
        p = dao.leerPorId(identificacionTF.getText());
        if (p.getNombrePaciente1() != null) {
            nombre1L.setText("Nombre 1: " + p.getNombrePaciente1());
            nombre2L.setText("Nombre 2: " + p.getNombrePaciente2());
            apellido1L.setText("Apellido 1: " + p.getApellidoPaciente1());
            apellido2L.setText("Apellido 2: " + p.getApellidoPaciente2());
        } else {
          //  JOptionPane.showMessageDialog(null, "Paciente no encontrado", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        if (p.getNombrePaciente1() != null) {
            dao.ActualizarEstado(identificacionTF.getText());
           // JOptionPane.showMessageDialog(null, "Paciente egresado con éxito", "Aceptado", JOptionPane.INFORMATION_MESSAGE);
             System.out.println("Paciente egresado con éxito");
        } else {
            System.out.println("PACIENTE NO ENCONTRADO");
            
        }
    }//GEN-LAST:event_aceptarBActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void registroTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registroTFActionPerformed

    private void BuscarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarBActionPerformed
        Paciente p = new Paciente();
        PacienteDAO_prov dao = new PacienteDAO_prov();
        p = dao.leerPorId(identificacionTF.getText());
        if (p.getNombrePaciente1() != null) {
            nombre1L.setText("Nombre 1: " + p.getNombrePaciente1());
            nombre2L.setText("Nombre 2: " + p.getNombrePaciente2());
            apellido1L.setText("Apellido 1: " + p.getApellidoPaciente1());
            apellido2L.setText("Apellido 2: " + p.getApellidoPaciente2());
        } else {
           // JOptionPane.showMessageDialog(null, "Paciente no encontrado", "Advertencia", JOptionPane.WARNING_MESSAGE);
            //  JOptionPane.showMessageDialog(null, "Mensaje dentro de la ventana", "Mensaje en la barra de titulo", JOptionPane.WARNING_MESSAGE);
            System.out.println("Paciente no encontrado");
        }

    }//GEN-LAST:event_BuscarBActionPerformed

    private void identificacionTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identificacionTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identificacionTFActionPerformed

    private void bombaNutricionCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bombaNutricionCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bombaNutricionCBActionPerformed

    private void cancelarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBActionPerformed
        nombre1L.setText("Nombre 1");
        nombre2L.setText("Nombre 2");
        apellido1L.setText("Apellido 1");
        apellido2L.setText("Apellido 2");
        registroTF.setText("");
        observacionTF.setText("");
        identificacionTF.setText("");

// TODO add your handling code here:
    }//GEN-LAST:event_cancelarBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarB;
    private javax.swing.JButton aceptarB;
    private javax.swing.JLabel apellido1L;
    private javax.swing.JLabel apellido2L;
    private javax.swing.JCheckBox bombaNutricionCB;
    private javax.swing.JButton cancelarB;
    private javax.swing.JPanel equiposUsados;
    private javax.swing.JLabel fechaL;
    private javax.swing.JTextField identificacionTF;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel nombre1L;
    private javax.swing.JLabel nombre2L;
    private javax.swing.JTextField observacionTF;
    private javax.swing.JTextField registroTF;
    private javax.swing.JLabel regitroL;
    private javax.swing.JLabel rethusL;
    private javax.swing.JLabel tipoAtencioL;
    private javax.swing.JLabel tipoAtencionL;
    // End of variables declaration//GEN-END:variables
}
