/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import DAO.CamaDAO;
import DAO.EgresoPacienteDAO;
import DAO.IngresoPacienteDAO;
import DAO.PacienteDAO_prov;
import Entidad.Camas;
import Entidad.EgresoPaciente;
import Entidad.Paciente;
import javax.swing.JOptionPane;
import Entidad.IngresoPaciente;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Observable;

/**
 *
 * @author tech
 */
public class EgresoPacienteFrontera extends javax.swing.JPanel {
    
    private Paciente paciente = new Paciente();
    private IngresoPaciente ingp = new IngresoPaciente();
    /**
     * Creates new form IngresoPaciente
     */
    public EgresoPacienteFrontera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        identificacionTF = new javax.swing.JTextField();
        nombre1L = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        observacionTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        aceptarB = new javax.swing.JButton();
        cancelarB = new javax.swing.JButton();
        nombre2L = new javax.swing.JLabel();
        apellido1L = new javax.swing.JLabel();
        apellido2L = new javax.swing.JLabel();
        tipoAtencioL = new javax.swing.JLabel();
        tipoAtencionL = new javax.swing.JLabel();
        fechaL = new javax.swing.JLabel();
        rethusL = new javax.swing.JLabel();
        BuscarB = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(755, 585));
        setPreferredSize(new java.awt.Dimension(755, 585));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        identificacionTF.setBackground(new java.awt.Color(204, 204, 204));
        identificacionTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identificacionTFActionPerformed(evt);
            }
        });
        add(identificacionTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 6, 145, -1));

        nombre1L.setBackground(new java.awt.Color(0, 0, 0));
        nombre1L.setText("Nombre 1");
        add(nombre1L, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("No. Identificación");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 12, -1, -1));

        observacionTF.setBackground(new java.awt.Color(102, 102, 102));
        add(observacionTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 234, 124));

        jLabel7.setText("Observaciones");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        aceptarB.setBackground(new java.awt.Color(204, 204, 204));
        aceptarB.setText("Aceptar");
        aceptarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarBActionPerformed(evt);
            }
        });
        add(aceptarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 83, -1));

        cancelarB.setBackground(new java.awt.Color(204, 204, 204));
        cancelarB.setText("Cancelar");
        cancelarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBActionPerformed(evt);
            }
        });
        add(cancelarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, -1, -1));

        nombre2L.setBackground(new java.awt.Color(0, 0, 0));
        nombre2L.setText("Nombre 2");
        add(nombre2L, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        apellido1L.setBackground(new java.awt.Color(0, 0, 0));
        apellido1L.setText("Apellido 1");
        add(apellido1L, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        apellido2L.setBackground(new java.awt.Color(0, 0, 0));
        apellido2L.setText("Apellido 2");
        add(apellido2L, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 81, -1, -1));

        tipoAtencioL.setBackground(new java.awt.Color(0, 0, 0));
        tipoAtencioL.setText("Tipo de atención");
        add(tipoAtencioL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 102, -1, -1));

        tipoAtencionL.setBackground(new java.awt.Color(0, 0, 0));
        tipoAtencionL.setText("No. de cama");
        add(tipoAtencionL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 123, -1, -1));

        fechaL.setText("Fecha");
        add(fechaL, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, -1, -1));

        rethusL.setText("ReTHUS");
        add(rethusL, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, -1, -1));

        BuscarB.setText("Buscar");
        BuscarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarBActionPerformed(evt);
            }
        });
        add(BuscarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarBActionPerformed
        /*
        IF(INGRESO != NULL){
            //EGRESO(INGRESO, OBS);
            INGRESO.SETESTADO(FALSE);
            IDAO.ACTUALIZAR(INGRESO);
        
            INGRESO.GETCAMA
            CAMAUX = CDAO.LEER(GETCAMA)
            CAMAUX.SETESTADO(FALSE);
            CDAO.ACTUALIZAR(CAMA, CAMAUX);
        
        
            LISTA<EQUSADOS> = SELECT * EQUIPOS USADOS WHERE INGRESOP_IDINGRESO=INGRESO.GETID():
            FOR(EQ IN EQUSADOS){
                EQUIPO = EDAO.LEERPORID(EQ.GETEQUIPO_IDEQUIPO)
                EQUIPO.SETESTADO(FALSE);
                EDAO.ACTUALIZAR(EQUIPO);
            } ELSE {"no se puede egresar"}
        */
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
                LocalDateTime now = LocalDateTime.now();
                String fecha = now.format(dtf);
        
        if(this.ingp.getIdIngreso()!=0){
            IngresoPaciente ingpaux = new IngresoPaciente();
            IngresoPacienteDAO idao = new IngresoPacienteDAO();
            
            Camas camaaux = new Camas();
            CamaDAO cdao = new CamaDAO();
            
            EgresoPacienteDAO edao = new EgresoPacienteDAO();
            EgresoPaciente egreso = new EgresoPaciente();
            egreso.setFecha(fecha);
            egreso.setObservaciones(observacionTF.getText());
            egreso.setIngresoP(this.ingp);
            edao.crear(egreso);
            
            //actualizo estado ingreso
            ingpaux = this.ingp;
            ingpaux.setEstado(false);
            idao.actualizar(ingp, ingpaux);
            
            //actualizo estado cama
            camaaux = this.ingp.getCama();
            camaaux.setEstado(false);
            cdao.actualizar(this.ingp.getCama(), camaaux);
            
            limpiar();
            
        } else {
            System.out.println("NO SE PUEDE EGRESAR, INGRESO NO DISPONIBLE");
        }
    }//GEN-LAST:event_aceptarBActionPerformed

    private void BuscarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarBActionPerformed
        
        //BUSCAR SELECT * FROM INGRESOPACIENTE WHERE PACIENTE_IDPACIENTE = idpaciente AND ESTADO = true;
        //if(ingresopaciente != null){ Paciente P = Pdao.leerporid(P.getIdPaciente()) }
        //else{ sout("PACIENTE SIN INGRESOS ACTIVOS") }
        
        String idpaciente = identificacionTF.getText();
        IngresoPacienteDAO ingpdao = new IngresoPacienteDAO();
        this.ingp = ingpdao.leerPorPaciente(idpaciente);
        if(this.ingp.getIdIngreso() != 0){
            this.paciente = ingp.getPaciente();
            nombre1L.setText("Nombre 1: " + this.paciente.getNombrePaciente1());
            nombre2L.setText("Nombre 2: " + this.paciente.getNombrePaciente2());
            apellido1L.setText("Apellido 1: " + this.paciente.getApellidoPaciente1());
            apellido2L.setText("Apellido 2: " + this.paciente.getApellidoPaciente2());
            tipoAtencioL.setText("Tipo de atencion: " + this.ingp.getCama().getPabellon());
            tipoAtencionL.setText("No. de Cama: " + Integer.toString(this.ingp.getCama().getIdCamas()));
            fechaL.setText("Fecha: " + this.ingp.getFecha());
            rethusL.setText("reTHUS: " + this.ingp.getPersonalm().getReTHUS());
        }
        else {
            System.out.println("PACIENTE SIN INGRESOS ACTIVOS");
        }
        
        
    }//GEN-LAST:event_BuscarBActionPerformed

    private void identificacionTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identificacionTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identificacionTFActionPerformed

    private void cancelarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBActionPerformed
        limpiar();

// TODO add your handling code here:
    }//GEN-LAST:event_cancelarBActionPerformed
    public void limpiar(){
        nombre1L.setText("Nombre 1");
        nombre2L.setText("Nombre 2");
        apellido1L.setText("Apellido 1");
        apellido2L.setText("Apellido 2");
        observacionTF.setText("");
        identificacionTF.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarB;
    private javax.swing.JButton aceptarB;
    private javax.swing.JLabel apellido1L;
    private javax.swing.JLabel apellido2L;
    private javax.swing.JButton cancelarB;
    private javax.swing.JLabel fechaL;
    private javax.swing.JTextField identificacionTF;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel nombre1L;
    private javax.swing.JLabel nombre2L;
    private javax.swing.JTextField observacionTF;
    private javax.swing.JLabel rethusL;
    private javax.swing.JLabel tipoAtencioL;
    private javax.swing.JLabel tipoAtencionL;
    // End of variables declaration//GEN-END:variables

}
