/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import Control.ValidarLogin;
import Entidad.PersonalMedico;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author tech
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usuarioTF = new javax.swing.JTextField();
        ingresarB = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        registrarB = new javax.swing.JButton();
        iniciarAdminB = new javax.swing.JButton();
        mensajeUsuario1 = new javax.swing.JLabel();
        mensajeUsuario = new javax.swing.JLabel();
        contraseniaTF = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Autenticación Personal Médico");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(63, 191, 168));
        jLabel1.setText("Personal Médico");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        usuarioTF.setBackground(new java.awt.Color(16, 65, 56));
        usuarioTF.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        usuarioTF.setForeground(new java.awt.Color(63, 191, 168));
        usuarioTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usuarioTF.setText("Usuario");
        usuarioTF.setBorder(null);
        usuarioTF.setFocusCycleRoot(true);
        usuarioTF.setOpaque(false);
        usuarioTF.setSelectedTextColor(new java.awt.Color(16, 65, 56));
        usuarioTF.setSelectionColor(new java.awt.Color(63, 191, 168));
        usuarioTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usuarioTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usuarioTFFocusLost(evt);
            }
        });
        usuarioTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioTFActionPerformed(evt);
            }
        });
        jPanel1.add(usuarioTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 205, 190, 30));

        ingresarB.setBackground(new java.awt.Color(18, 62, 54));
        ingresarB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Iniciar_sesion.png"))); // NOI18N
        ingresarB.setBorder(null);
        ingresarB.setContentAreaFilled(false);
        ingresarB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ingresarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarBActionPerformed(evt);
            }
        });
        jPanel1.add(ingresarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 220, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 8)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(18, 62, 54));
        jLabel3.setText("Version 2.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, -1, -1));

        registrarB.setBackground(new java.awt.Color(204, 204, 204));
        registrarB.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        registrarB.setForeground(new java.awt.Color(63, 191, 168));
        registrarB.setText("Registrar un administrador");
        registrarB.setBorder(null);
        registrarB.setContentAreaFilled(false);
        registrarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarBActionPerformed(evt);
            }
        });
        jPanel1.add(registrarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 420, 190, -1));

        iniciarAdminB.setBackground(new java.awt.Color(204, 204, 204));
        iniciarAdminB.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        iniciarAdminB.setForeground(new java.awt.Color(63, 191, 168));
        iniciarAdminB.setText("Iniciar cómo administrador");
        iniciarAdminB.setBorder(null);
        iniciarAdminB.setContentAreaFilled(false);
        iniciarAdminB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarAdminBActionPerformed(evt);
            }
        });
        jPanel1.add(iniciarAdminB, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 200, -1));

        mensajeUsuario1.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        mensajeUsuario1.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(mensajeUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 148, -1, -1));

        mensajeUsuario.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        mensajeUsuario.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(mensajeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        contraseniaTF.setBackground(new java.awt.Color(16, 65, 56));
        contraseniaTF.setEchoChar('\u25CF');
        contraseniaTF.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        contraseniaTF.setForeground(new java.awt.Color(63, 191, 168));
        contraseniaTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contraseniaTF.setText("contraseña");
        contraseniaTF.setBorder(null);
        contraseniaTF.setOpaque(false);
        contraseniaTF.setSelectedTextColor(new java.awt.Color(16, 65, 56));
        contraseniaTF.setSelectionColor(new java.awt.Color(63, 191, 168));
        contraseniaTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contraseniaTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                contraseniaTFFocusLost(evt);
            }
        });
        contraseniaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseniaTFActionPerformed(evt);
            }
        });
        jPanel1.add(contraseniaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 180, 30));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, -1, -1));

        Fondo.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        Fondo.setForeground(new java.awt.Color(63, 191, 168));
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Login.jpg"))); // NOI18N
        Fondo.setRequestFocusEnabled(false);
        Fondo.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarAdminBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarAdminBActionPerformed
        new LoginAdmin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_iniciarAdminBActionPerformed

    private void registrarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarBActionPerformed
        new RegistroAdmin().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_registrarBActionPerformed

    private void ingresarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarBActionPerformed
        PersonalMedico usuario = new PersonalMedico();
        usuario.setNomUsuario(usuarioTF.getText());
        usuario.setPasswordAux(String.valueOf(contraseniaTF.getPassword()));

        ValidarLogin Validar = new ValidarLogin();

        System.out.println("---------------------------------------------------**-");
        String resultado = Validar.verificarLogin(usuario);

        if (!Validar.VerificarLongitudNombre(usuarioTF.getText())) {
            mensajeUsuario.setText("Longitud de nombre incorrecta");
        } else {
            mensajeUsuario.setText("");
        }
        if (!Validar.VerificarLongitudPassword(String.valueOf(contraseniaTF.getPassword()))) {
            mensajeUsuario1.setText("Longitud de contraseña incorrecto");
        } else {
            mensajeUsuario1.setText("");
        }
        if (resultado.equals("Bienvenido")) {
            new FramePrincipalPersonalMedico().setVisible(true);
            this.dispose();
        }
        if (resultado.equals("Datos incorrectos")) {
            JOptionPane.showMessageDialog(null, "Datos incorrectos", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        System.out.println(resultado);         // TODO add your handling code here:
    }//GEN-LAST:event_ingresarBActionPerformed

    private void contraseniaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseniaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseniaTFActionPerformed

    private void usuarioTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usuarioTFFocusGained
        if(usuarioTF.getText().trim().toLowerCase().equals("usuario"))
        {
            usuarioTF.setText("");
            usuarioTF.setForeground(new java.awt.Color(63, 191, 168));
        }
    }//GEN-LAST:event_usuarioTFFocusGained

    private void usuarioTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioTFActionPerformed

    private void usuarioTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usuarioTFFocusLost
        if(usuarioTF.getText().trim().toLowerCase().equals("usuario")||usuarioTF.getText().trim().toLowerCase().equals(""))
        {
            usuarioTF.setText("Usuario");
            usuarioTF.setForeground(new java.awt.Color(63, 191, 168));
        }
    }//GEN-LAST:event_usuarioTFFocusLost

    private void contraseniaTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contraseniaTFFocusGained
        if(contraseniaTF.getText().trim().toLowerCase().equals("contraseña"))
        {
            contraseniaTF.setText("");
            contraseniaTF.setForeground(new java.awt.Color(63, 191, 168));
        }
    }//GEN-LAST:event_contraseniaTFFocusGained

    private void contraseniaTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contraseniaTFFocusLost
        if(contraseniaTF.getText().trim().toLowerCase().equals("contraseña")||contraseniaTF.getText().trim().toLowerCase().equals(""))
        {
            contraseniaTF.setText("contraseña");
            contraseniaTF.setForeground(new java.awt.Color(63, 191, 168));
        }
    }//GEN-LAST:event_contraseniaTFFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JPasswordField contraseniaTF;
    private javax.swing.JButton ingresarB;
    private javax.swing.JButton iniciarAdminB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mensajeUsuario;
    private javax.swing.JLabel mensajeUsuario1;
    private javax.swing.JButton registrarB;
    private javax.swing.JTextField usuarioTF;
    // End of variables declaration//GEN-END:variables
}
