/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import Control.ValidarRegistroEquipo;
import DAO.EquipoDAO;
import Entidad.Equipo;
import javax.swing.JOptionPane;

/**
 *
 * @author Diero I
 */
public class RegistroEquipo extends javax.swing.JPanel {

    /**
     * Creates new form RegistroEquipo
     */
    public RegistroEquipo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        equipoMarcaTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        equipoTipoCB = new javax.swing.JComboBox<>();
        equipoRegistroTF = new javax.swing.JTextField();
        aceptarB = new javax.swing.JButton();
        equipoCantidadTF = new javax.swing.JTextField();
        cancelarB = new javax.swing.JButton();
        equipoDescripcionTF = new javax.swing.JTextField();
        TipoDeEquipo = new javax.swing.JLabel();
        TipoEquipo = new javax.swing.JComboBox<>();
        mensajeUsuario = new javax.swing.JLabel();
        mensajeUsuario1 = new javax.swing.JLabel();
        mensajeUsuario2 = new javax.swing.JLabel();
        mensajeUsuario3 = new javax.swing.JLabel();
        mensajeUsuario4 = new javax.swing.JLabel();
        mensajeUsuario5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Marca");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 95, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Tipo de uso");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 139, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Registro Sanitario");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 183, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Cantidad");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 228, -1, -1));

        equipoMarcaTF.setBackground(new java.awt.Color(204, 204, 204));
        add(equipoMarcaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 89, 268, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Descripción");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 267, -1, -1));

        equipoTipoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Soporte de vida", "Quirúrgica", "Cuidados intensivos", "Terapia física", "Equipos de tratamiento", "Monitorización quirúrgica", "Monitorización de Cuidados intensivos", "Monitorización general", "Diagnósticos fisiológicos", "Analítica de laboratorio", "Accesorios de laboratorio", "Procesado de datos del paciente", "Otro" }));
        equipoTipoCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipoTipoCBActionPerformed(evt);
            }
        });
        add(equipoTipoCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 134, 270, -1));

        equipoRegistroTF.setBackground(new java.awt.Color(204, 204, 204));
        add(equipoRegistroTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 177, 268, -1));

        aceptarB.setBackground(new java.awt.Color(204, 204, 204));
        aceptarB.setText("Aceptar");
        aceptarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarBActionPerformed(evt);
            }
        });
        add(aceptarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, 83, -1));

        equipoCantidadTF.setBackground(new java.awt.Color(204, 204, 204));
        add(equipoCantidadTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 222, 268, -1));

        cancelarB.setBackground(new java.awt.Color(204, 204, 204));
        cancelarB.setText("Cancelar");
        cancelarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBActionPerformed(evt);
            }
        });
        add(cancelarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 445, -1, -1));

        equipoDescripcionTF.setBackground(new java.awt.Color(204, 204, 204));
        add(equipoDescripcionTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 267, 196, 120));

        TipoDeEquipo.setBackground(new java.awt.Color(0, 0, 0));
        TipoDeEquipo.setText("Tipo De Equipo");
        add(TipoDeEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 50, -1, -1));

        TipoEquipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ","VENTILADOR MECANICO", "SATUROMETRO", "BALA OXIGENO", "MONITOR", "BOMBA INFUSION CONTINUA", "BOMBA NUTRICION ENTERAL", "ASPIRADOR DE SECRECIONES","EQUIPO DE INTUBACION" }));
        add(TipoEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 270, -1));

        mensajeUsuario.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        mensajeUsuario.setForeground(new java.awt.Color(255, 0, 0));
        add(mensajeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 75, -1, -1));

        mensajeUsuario1.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        mensajeUsuario1.setForeground(new java.awt.Color(255, 0, 0));
        add(mensajeUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 115, -1, -1));

        mensajeUsuario2.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        mensajeUsuario2.setForeground(new java.awt.Color(255, 0, 0));
        add(mensajeUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 159, -1, -1));

        mensajeUsuario3.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        mensajeUsuario3.setForeground(new java.awt.Color(255, 0, 0));
        add(mensajeUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 201, -1, -1));

        mensajeUsuario4.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        mensajeUsuario4.setForeground(new java.awt.Color(255, 0, 0));
        add(mensajeUsuario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 248, -1, -1));

        mensajeUsuario5.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        mensajeUsuario5.setForeground(new java.awt.Color(255, 0, 0));
        add(mensajeUsuario5, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 385, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void equipoTipoCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipoTipoCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equipoTipoCBActionPerformed

    private void aceptarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarBActionPerformed
        Equipo equipo = new Equipo();
        EquipoDAO dao = new EquipoDAO();
        int cantidad = 0;
        equipo.setNombreEquipo(TipoEquipo.getSelectedItem().toString());
        equipo.setMarca(equipoMarcaTF.getText());
        equipo.setTipoUso(equipoTipoCB.getSelectedItem().toString());
        equipo.setRegistroSanitario(equipoRegistroTF.getText());
        equipo.setDescripcionEquipo(equipoDescripcionTF.getText());
        equipo.setEstadoEquipo(false);

        ValidarRegistroEquipo validar = new ValidarRegistroEquipo();
        System.out.println("-------");
        String resultado = validar.VerificarRegistroEquipo(equipo);
        System.out.println(resultado);
        if (" ".equals(TipoEquipo.getSelectedItem().toString())) {
            mensajeUsuario.setText("No se ha seleccionado el tipo de equipo");
        } else {
            mensajeUsuario.setText("");
        }
        if (!validar.VerificarLongitudMarca(equipoMarcaTF.getText())) {
            mensajeUsuario1.setText("Longitud marca incorrecta");
        } else {
            mensajeUsuario1.setText("");
        }
        if (" ".equals(equipoTipoCB.getSelectedItem().toString())) {
            mensajeUsuario2.setText("No se ha seleccionado el tipo de uso");
        } else {
            mensajeUsuario2.setText("");
        }
        if (!validar.VerificarLongitudRegistroSanitarioEquipo(equipoRegistroTF.getText())) {
            mensajeUsuario3.setText("Longitud Registro Sanitario incorrecta");
        } else {
            mensajeUsuario3.setText("");
        }
        //por mejorar
        if (equipoCantidadTF.getText().length() == 0) {
            mensajeUsuario4.setText("No hay Cantidad");
        } else {
            if (!validar.VerificarLongitudCantidadEquipo(Integer.parseInt(equipoCantidadTF.getText()))) {
                mensajeUsuario4.setText("Longitud de cantidad incorrecta");
                cantidad = 0;
            } else {
                mensajeUsuario4.setText("");
                cantidad = Integer.parseInt(equipoCantidadTF.getText());
            }
        }
        if (!validar.VerificarLongitudRegistroSanitarioEquipo(equipoDescripcionTF.getText())) {
            mensajeUsuario4.setText("Longitud de descripción incorrecta");
        } else {
            mensajeUsuario4.setText("");
        }

        if (resultado == "Datos ingresados correctamente" && validar.VerificarLongitudCantidadEquipo(cantidad)) {
            for (int i = 1; i <= Integer.parseInt(equipoCantidadTF.getText()); i++) {
                dao.crear(equipo);
            }
            System.out.println("Equipos registrados correctamente");
            JOptionPane.showMessageDialog(null, "Equipos registrados correctamente", "", JOptionPane.INFORMATION_MESSAGE);
            borrar();
        }
    }//GEN-LAST:event_aceptarBActionPerformed

    private void cancelarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBActionPerformed
        borrar();
    }//GEN-LAST:event_cancelarBActionPerformed
    public void borrar() {
        equipoCantidadTF.setText("");
        equipoDescripcionTF.setText("");
        equipoMarcaTF.setText("");
        equipoRegistroTF.setText("");
        equipoTipoCB.setSelectedItem(" ");
        TipoEquipo.setSelectedItem(" ");
        mensajeUsuario.setText("");
        mensajeUsuario1.setText("");
        mensajeUsuario2.setText("");
        mensajeUsuario3.setText("");
        mensajeUsuario4.setText("");
        mensajeUsuario5.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TipoDeEquipo;
    private javax.swing.JComboBox<String> TipoEquipo;
    private javax.swing.JButton aceptarB;
    private javax.swing.JButton cancelarB;
    private javax.swing.JTextField equipoCantidadTF;
    private javax.swing.JTextField equipoDescripcionTF;
    private javax.swing.JTextField equipoMarcaTF;
    private javax.swing.JTextField equipoRegistroTF;
    private javax.swing.JComboBox<String> equipoTipoCB;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel mensajeUsuario;
    private javax.swing.JLabel mensajeUsuario1;
    private javax.swing.JLabel mensajeUsuario2;
    private javax.swing.JLabel mensajeUsuario3;
    private javax.swing.JLabel mensajeUsuario4;
    private javax.swing.JLabel mensajeUsuario5;
    // End of variables declaration//GEN-END:variables
}
