/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import Control.ValidarRegistroCamas;
import DAO.CamaDAO;
import Entidad.Camas;

/**
 *
 * @author user
 */
public class RegistroCamas extends javax.swing.JPanel {

    /**
     * Creates new form RegistroCamas
     */
    public RegistroCamas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listaPabellonesCB = new javax.swing.JComboBox<>();
        camaUbicacionTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        aceptarB = new javax.swing.JButton();
        cancelarB = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaPabellonesCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Cuidados intensivos", "Cuidados intermedios" }));
        add(listaPabellonesCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 183, -1, -1));

        camaUbicacionTF.setBackground(new java.awt.Color(204, 204, 204));
        add(camaUbicacionTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 138, 166, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ubicación");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 144, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Pabellón");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 183, -1, -1));

        aceptarB.setBackground(new java.awt.Color(204, 204, 204));
        aceptarB.setForeground(new java.awt.Color(0, 0, 0));
        aceptarB.setText("Aceptar");
        aceptarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarBActionPerformed(evt);
            }
        });
        add(aceptarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 301, 83, -1));

        cancelarB.setBackground(new java.awt.Color(204, 204, 204));
        cancelarB.setForeground(new java.awt.Color(0, 0, 0));
        cancelarB.setText("Cancelar");
        cancelarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBActionPerformed(evt);
            }
        });
        add(cancelarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarBActionPerformed
        Camas camas = new Camas(); 
        CamaDAO dao = new CamaDAO();
        camas.setUbicacion(camaUbicacionTF.getText());
        camas.setPabellon(listaPabellonesCB.getSelectedItem().toString());
        camas.setEstado(false);
        
        ValidarRegistroCamas validar = new ValidarRegistroCamas();
        System.out.println("---------");
        String resultado = validar.VerificarRegistroCamas(camas);
        System.out.println(resultado);
        
        if("Cama Registrada Correctamente".equals(resultado)){
            dao.crear(camas);
        }
    }//GEN-LAST:event_aceptarBActionPerformed

    private void cancelarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBActionPerformed
  camaUbicacionTF.setText("");
       
            // TODO add your handling code here:
    }//GEN-LAST:event_cancelarBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarB;
    private javax.swing.JTextField camaUbicacionTF;
    private javax.swing.JButton cancelarB;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> listaPabellonesCB;
    // End of variables declaration//GEN-END:variables
}
